spring.application.name=chat-app
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/chatapp
spring.datasource.username= hika
spring.datasource.password= Hikaru16
spring.flyway.baselineOnMigrate=true

spring.thymeleaf.cache=false
spring.web.resources.chain.cache=false